# Generated by Django 2.0.6 on 2018-06-07 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('uri', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('title', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=64)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('end_inscrip_date', models.DateField()),
                ('max_place_student', models.IntegerField()),
                ('max_place_ext', models.IntegerField()),
                ('price_student', models.IntegerField()),
                ('price_extern', models.IntegerField()),
                ('display_available_places', models.NullBooleanField()),
                ('premium', models.NullBooleanField()),
                ('status', models.IntegerField(default=0)),
                ('nb_registered', models.IntegerField(default=0)),
                ('nb_registered_used', models.IntegerField(default=0)),
                ('nb_registered_inside', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.CharField(default='', max_length=64, primary_key=True, serialize=False)),
                ('email_ticket', models.CharField(max_length=64)),
                ('password', models.CharField(default='', max_length=64)),
                ('login', models.CharField(max_length=64)),
                ('firstname', models.CharField(default='', max_length=64)),
                ('lastname', models.CharField(default='', max_length=64)),
                ('student', models.NullBooleanField()),
                ('access_level', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Userassociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('association_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billeterie.Association')),
                ('members_mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billeterie.User')),
            ],
        ),
        migrations.CreateModel(
            name='Userevent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billet_type', models.IntegerField()),
                ('inside', models.BooleanField()),
                ('staff', models.BooleanField(default=False)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billeterie.Event')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billeterie.User')),
            ],
        ),
    ]
