# Generated by Django 2.0.6 on 2018-06-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billeterie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='display_available_places',
            field=models.BooleanField(),
        ),
    ]
