# Generated by Django 2.0.6 on 2018-06-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billeterie', '0002_auto_20180607_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='display_available_places',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='premium',
            field=models.NullBooleanField(),
        ),
    ]
