# Generated by Django 2.0.6 on 2018-06-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billetterie', '0002_auto_20180608_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='userevent',
            name='token',
            field=models.CharField(default='NOPE', max_length=64),
        ),
    ]
